### ISSUE TITLE
[Bug]: Windows cargo build fails on get_clipboard(FileList) (E0282)

### ISSUE THREAD

**Issue by zhangxaochen** [RongleCat/grok-app#763]
### Describe the bug

Windows `cargo check` / `pnpm build:win` fails after #756:

```
error[E0282]: type annotations needed
   --> src\commands\fs.rs:149:27
    |
149 |         if let Ok(list) = get_clipboard(formats::FileList) {
    |                           ^^^^^^^^^^^^^ cannot infer type of the type parameter `R`
```

`clipboard-win` 5.4 implements `Getter` for `FileList` as both `Vec<String>` and `Vec<PathBuf>`, so rustc cannot infer `get_clipboard`. Linux/macOS CI stay green because this path is `#[cfg(windows)]`.

This is not a product rename. Follow-up to #755 / #756 (Explorer file paste via `CF_HDROP`).

### Steps to reproduce

1. Check out `main` on Windows (MSVC).
2. `cd src-tauri && cargo check --target x86_64-pc-windows-msvc`
3. Compile stops at `src/commands/fs.rs` `get_clipboard(formats::FileList)`.

### Expected behavior

Windows Host builds. `clipboard_file_paths` still returns `Vec<String>` from `CF_HDROP`.

### App version

`main` after #756 (`0.2.23` Unreleased). CI `Rust Windows` has been red since that merge (e.g. run 32392194572).

### Grok Build CLI version (if known)

n/a (Host compile)

### OS

Windows

### Logs / screenshots

Same E0282 as GitHub Actions `Rust Windows` on the #756 merge commit. Fix is `get_clipboard::<Vec<String>, _>(formats::FileList)`.
