### PR TITLE
fix(windows): name clipboard FileList as Vec<String>

### LINKED ISSUE #763: [Bug]: Windows cargo build fails on get_clipboard(FileList) (E0282)
### Describe the bug

Windows `cargo check` / `pnpm build:win` fails after #756:

```
error[E0282]: type annotations needed
   --> src\commands\fs.rs:149:27
    |
149 |         if let Ok(list) = get_clipboard(formats::FileList) {
    |                           ^^^^^^^^^^^^^ cannot infer type of the type parameter `R`
```

`clipboard-win` 5.4 implements `Getter` for `FileList` as both `Vec<String>` and `Vec<PathBuf>`, so rustc cannot infer `get_clipboard`. Linux/macOS CI stay green because this path is `#[cfg(windows)]`.

This is not a product rename. Follow-up to #755 / #756 (Explorer file paste via `CF_HDROP`).

### Steps to reproduce

1. Check out `main` on Windows (MSVC).
2. `cd src-tauri && cargo check --target x86_64-pc-windows-msvc`
3. Compile stops at `src/commands/fs.rs` `get_clipboard(formats::FileList)`.

### Expected behavior

Windows Host builds. `clipboard_file_paths` still returns `Vec<String>` from `CF_HDROP`.

### App version

`main` after #756 (`0.2.23` Unreleased). CI `Rust Windows` has been red since that merge (e.g. run 32392194572).

### Grok Build CLI version (if known)

n/a (Host compile)

### OS

Windows

### Logs / screenshots

Same E0282 as GitHub Actions `Rust Windows` on the #756 merge commit. Fix is `get_clipboard::<Vec<String>, _>(formats::FileList)`.

### PR DESCRIPTION
**Pull request by zhangxaochen**
## Summary
- Windows Host `cargo check` / `pnpm build:win` has been red since #756: `clipboard-win` 5.4’s `FileList` implements `Getter` for both `Vec<String>` and `Vec<PathBuf>`, so rustc cannot infer `get_clipboard` (`E0282`).
- Name the result `Vec<String>` to match `clipboard_file_paths_os`. Runtime paste path is unchanged.
- CHANGELOG Unreleased (en + zh).

Fixes #763

## Type of change
- [x] Bug fix
- [ ] New feature
- [ ] Documentation
- [ ] Refactor / chore

## Test plan
- [x] `cargo check --target x86_64-pc-windows-msvc` (this machine; E0282 gone)
- [x] `pnpm build:win` already succeeded with this annotation
- [ ] CI `Rust Windows` green
- [ ] Windows: copy a file in Explorer, paste into composer → still attaches `@path` (same as #756)

## Checklist
- [x] I ran `cargo check` in `src-tauri` for the Windows target
- [x] No UI strings / i18n
- [x] No `window.confirm` / `prompt` / `alert`
- [x] Docs / CHANGELOG Unreleased updated
- [x] No secrets

Note: `pi -p` is not installed on this Windows host (no `pi` on PATH; WSL has no bash). Per repo policy this is recorded rather than skipped silently.

### CODE REVIEW

**Comment by zhangxaochen** [comment]
CI 结论：

- `frontend` 绿，这次 diff 的 JS 侧没问题。
- Rust 三端都死在 **第一步** `cargo fmt --check`，还没编到 `fs.rs`，所以 **E0282 这次 CI 根本没跑到**。
- 格式差在 `session_manager/fork_trim.rs`（函数签名换行）和 `mod.rs`（`mod fork_trim` 排序）。这两处 **main 上已经红**（run 32432770535），不是 #764 引入的。
- 已补 `70cdf6af`：只 rustfmt 这两文件，让 CI 能越过 fmt 去编 Windows Host。

**Review by RongleCat — APPROVED** [review]
LGTM. `clipboard-win` 5.4 FileList 同时 impl `Getter<Vec<String>>` 和 `Getter<Vec<PathBuf>>`，显式 `get_clipboard::<Vec<String>, _>` 是最小正确修复。附带 rustfmt `fork_trim`/`mod.rs` 把 main 上已红的 `cargo fmt --check` 一并修绿。CHANGELOG Unreleased 只追加。CI 四门全绿。

pi `-p`（read/bash）无 blocker。squash-merge，Fixes #763。

**Comment by RongleCat** [comment]
Thanks @zhangxaochen — squash-merged as `11999b5c`. Windows Host 在 #756 之后编不过的 E0282 修好了，顺带把 main 上已红的 `cargo fmt --check` 一并带绿。#763 已关。
